{
  "hash": "306846e610c8c6171b3d5c1df63c4261",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Probability Calculations for Means (Reading)\"\n---\n\n\n\n\n## Review of Sampling Distributions\n\nWhen is the sample mean normally distributed?  This happens when either of the two conditions are satisfied:\n\n- The population is normally distributed, so the sample mean is automatically normally distributed.\n- The sample size is large, and the Central Limit Theorem implies that the sample mean is normally distributed.\n\nFor the mean of draws from a random variable with mean $\\mu$ and standard deviation $\\sigma$, the following are true:\n\n- The mean of the random variable  $\\bar X$ is $\\mu$.\n- The standard deviation of the random variable $\\bar X$ is $\\displaystyle{\\frac{\\sigma}{\\sqrt{n}}}$.  \n\nPreviously, you learned how to use the normal probability applet and R to convert a $z$-score to a corresponding area under the curve.  These skills will be applied again in this activity.  The following questions will help you brush up on how to calculate probabilities for a normal distribution.\n\n<center>\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images/L04_A06_Graph.jpg)\n\n</center>\n<br>\n\n<div class=\"QuestionsHeading\">Answer the following questions:</div>\n<div class=\"Questions\">\n1. Look at the output from the applet, given above. What is the probability that a standard normal random variable will be below 1.25?\n\n<details>\n<summary>Show/Hide Solution</summary>\n<center>$0.8944$</center>\n</details>\n\n1a. Compare this to the R output using `pnorm()`\n\n<details>\n<summary>Show/Hide Solution</summary>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1.25)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8943502\n```\n\n\n:::\n:::\n\n\n\n\n</details>\n\n2. Look at the output from the applet given above.  What is the probability that a standard normal random variable will be above 1.25?\n\n<details>\n<summary>Show/Hide Solution</summary>\n<center>$1 - 0.8944 = 0.1056$</center>\n</details>\n\n3. Challenge problem:  Use R to determine the probability that a standard normal random variable will be between -1.3 and 1.25.\n\n<details>\n<summary>Show/Hide Solution</summary>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1.25) - pnorm(-1.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7975497\n```\n\n\n:::\n:::\n\n\n\n</details>\n\n4. Use R to find the probability that a standard normal random variable will be greater than -0.75.\n\n<details>\n<summary>Show/Hide Solution</summary>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1-pnorm(-.75)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7733726\n```\n\n\n:::\n\n```{.r .cell-code}\n# Equivalantly \npnorm(-.75, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7733726\n```\n\n\n:::\n:::\n\n\n\n\n</details>\n\n5. If the mean of a normally distributed random variable is -23 and the standard deviation is 7, what is the probability that the random variable will have a value that is less than -25?\n\n<details>\n<summary>Show/Hide Solution</summary>\n* The $z$-score is:\n<br>\n<center>\n$\\displaystyle{z = \\frac{-25 - (-23)}{7} = -0.2857}$\n</center>\n<br>\nUsing R:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- -25\nmu <- -23\nsigma <- 7\n\nz <- (x-mu)/sigma\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2857143\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3875485\n```\n\n\n:::\n:::\n\n\n\n*We find that the area to the left of $z$ = -0.2857 is $0.3876$.\n</details>\n</div>\n<br>\n\n## Probabilities Involving a Mean\n\nIf the sample mean is normally distributed, then we can consider the sample mean, $\\bar x$, as one observation from a normal distribution with mean $\\mu$ and standard deviation $\\displaystyle{\\frac{\\sigma}{\\sqrt{n}}}$. With this in mind, we can compute the $z$-score for any value of this random variable:\n\n$$z = \\frac{\\text{value} - \\text{mean}}{\\text{standard deviation}}=\\frac{\\bar x-\\mu}{\\sigma / \\sqrt{n} }$$\n\nNotice that we just replaced the \"value\" with the normal random variable, the \"mean\" with its mean and \"standard deviation\" with its standard deviation.\n\nThe $z$-score follows a standard normal distribution. That is, it has a mean of 0 and a standard deviation of 1.  Now we can simply input the $z$-score into `pnorm()` to get the probability that a randomly selected mean will be above or below a given value of $\\bar x$.\n\n**Worked Example:  Finding the Area under a Normal Curve (Based on a Sample Mean)**\n\nAfter finding the $z$-score, we can use `pnorm()` to find the area under the curve (i.e. the probability.)  Suppose that a sample of size $n = 4$ has been drawn from a normal population with mean $\\mu = 7$ and standard deviation $\\sigma = 3$. Since the parent population is normal, we know the sampling distribution of the sample mean $\\bar x$ will be normal with mean $\\mu = 7$ and standard deviation $\\displaystyle{ \\frac{\\sigma}{\\sqrt{n}} = \\frac{3}{\\sqrt{4}} = 1.5}$. We can use this information to find the probability that $\\bar x$ will be greater than 10.\n\nThe $z$-score is\n\n$$z=\\frac{\\bar x-\\mu}{\\sigma / \\sqrt{n} } = \\frac{10 - 7}{3 / \\sqrt{4} }=2.0$$\n\nThe probability that $z$ will be greater than $2.00$ is the area under the standard normal distribution to the right of $2.00$.  We find this area using the normal probability using R:\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images/L04_A06_Graph_2.jpg)\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 10\nmu <- 7\nsigma <- 3\nn <- 4\nsigma_xbar <- sigma/sqrt(n)\n\nz <- (xbar-mu)/sigma_xbar\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\n#Area to the left:\npnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9772499\n```\n\n\n:::\n\n```{.r .cell-code}\n#Area to the right:\n1-pnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02275013\n```\n\n\n:::\n:::\n\n\n\n\n\nThe area to the right of $z = 2.00$ is $0.02275$.  This is the probability that the random sample of $n = 4$ items will have a *mean* that is greater than $10$.\n\nIn this example, the sample mean was automatically normally distributed because the parent population was normally distributed.  This will always be true, no matter what size sample is drawn.\n\n**Worked Example:  Finding the Area under a Normal Curve (Based on a Sample Mean)**\n\nWhat do we do if the parent population is not normally distributed?  If the sample size is large, then the Central Limit Theorem guarantees that the sample mean will be approximately normally distributed.  Based on this, we can still do normal probability calculations for the mean of a random sample.\n\nThe distribution of the weekly costs incurred by Global Solutions Unlimited is right skewed.  The population mean of the costs is \\$26,400 and the standard deviation is \\$23,200.  A random sample of $n = 40$ weeks is to be selected, what is the probability that the mean weekly costs will be less than \\$20,000?\n\nSince the number of observations  is large, the Central Limit Theorem assures that the sample mean will follow a normal distribution.  The $z$-score for $\\bar x =$ \\$20,000 is:\n\n$$z = \\frac{\\bar x-\\mu}{\\sigma / \\sqrt{n} } = \\frac{20,000-26,400}{23,200 / \\sqrt{40}} = -1.745 $$\n\nUsing R, we can find the area to the left of this $z$-score:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- 20000\nmu <- 26400\nsigma <- 23200\nn <- 40\nsigma_xbar <- sigma/sqrt(n)\n\nz <- (xbar-mu) / sigma_xbar\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.744705\n```\n\n\n:::\n\n```{.r .cell-code}\n#Area to the left:\npnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04051812\n```\n\n\n:::\n\n```{.r .cell-code}\n#Area to the right:\n1-pnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9594819\n```\n\n\n:::\n:::\n\n\n\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images//L04_A06_Graph_3.jpg)\n\n\n__NOTE__:  Recall the the Normal Probabilty Applet rounds the $z$-scores first, then calculates the probabilities so they differ slightly from R.  \n\nThe area to the left of $z= -1.745$ is $0.04052$.  This is the probability that the mean costs for the $n = 40$ weeks will be less than \\$20,000.\n\n<br>\n\n#### Example: Environmental Clean Up\n\n<!-- This picture comes from http://happeningstock.deviantart.com/art/Grass-Hill-Area-Closed-Sign-255592183 and has an open license -->\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images//L07_AREA_CLOSED_sign.jpg)\n\nWe will now consider a complete example that shows how these probabilities are used in practice.\n\nThe United States Government decided to open some land near a uranium enrichment facility to public use.  After a few years of the public hiking, biking, and sometimes even hunting on this land, workers from the facility noticed that there were several unnatural-looking mounds in the earth near the area. Because this land was once used by the facility and nobody knew the origin of these piles, the government closed public access to the land until they could assess if the mounds were safe.\n\n\n<br>\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images/Step1.png)\n\n**Step 1: Design the study.**\n\nMeasurements were taken from the mounds to assess one of the contaminants, lead.  The tests involved are very expensive.  Each sample costs about \\$600 to process.\nThe Environmental Protection Agency (EPA) has set a \"No Action Level\" (NAL) for lead. If the mean concentration in the soil of the contaminant is less than the NAL, then the area can be declared safe for public use.  If the concentration of the contaminant reaches or exceeds the NAL, the site must be cleaned additionally before it is declared safe.  The NAL for lead is 50 milligrams of lead per kilogram of soil (mg/kg).\n\nThe hypothesis for this test are:\n\n$H_0:~~\\mu = 50 \\frac{\\text{mg}}{\\text{kg}}$\n\n$H_a:~~\\mu < 50 \\frac{\\text{mg}}{\\text{kg}}$\n\nIn environmental testing, we always assume the site is dirty.  That is, our null hypothesis is that the mean level of contamination is at the NAL.  We gather data to determine if there is sufficient evidence to support rejecting the null hypothesis.\n\n\n<br>\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images//Step2.png)\n\n**Step 2: Collect Data**\n\nScientists collected $n = 61$ measurements of the lead concentration in the soil, measured in mg/kg.  The data are given in the file [Uranium Plant Data-Lead](/Data/UraniumPlantData-Lead.xlsx){target=\"_blank}.\n\n\n<br>\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images/Step3.png)\n\n**Step 3: Describe the Data**\n\n<div class=\"QuestionsHeading\">Answer the following question:</div>\n<div class=\"Questions\">\n6. Create a histogram of the lead contamination data.\n\n\n<details>\n<summary>Show/Hide Solution</summary>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rio)\nlibrary(mosaic)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'mosaic'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:Matrix':\n\n    mean\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:ggplot2':\n\n    stat\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following object is masked from 'package:rio':\n\n    factorize\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nuranium <- import('https://github.com/byuistats/BYUI_M221_Book/raw/master/Data/UraniumPlantData-Lead.xlsx')\n\nhistogram(uranium$`Lead (mg/kg)`, xlab=\"Lead (mg/kg)\")\n```\n\n::: {.cell-output-display}\n![](07-Prob_Calculations_for_Means_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n</details>\n\n7. What is the shape of the distribution of the data?\n\n<details>\n<summary>Show/Hide Solution</summary>\n* The lead concentration data are right skewed.\n</details>\n\n8. Are any of the measured values above the NAL (50 mg/kg)?  What might this suggest?\n\n<details>\n<summary>Show/Hide Solution</summary>\n* Yes, there are several observations that are above the NAL.  This may suggest that the lead concentrations are very high in some isolated soil samples.  It may also be an indication of variability in the test results.\n</details>\n\n9. Visually, does it look like the mean lead concentration is less than 50 mg/kg?\n\n<details>\n<summary>Show/Hide Solution</summary>\n* Answers may vary.\n</details>\n\n10. What is the value of the sample mean?\n\n<details>\n<summary>Show/Hide Solution</summary>\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::kable(favstats(uranium$`Lead (mg/kg)`))\n```\n\n::: {.cell-output-display}\n\n\n|   | min|   Q1| median|   Q3| max|     mean|       sd|  n| missing|\n|:--|---:|----:|------:|----:|---:|--------:|--------:|--:|-------:|\n|   | 9.8| 14.1|   19.8| 33.1| 115| 29.13279| 23.26021| 61|       0|\n\n\n:::\n:::\n\n\n\n* The sample mean is 29.13 mg/kg.\n</details>\n</div>\n<br>\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images/Step4.png)\n\n\n**Step 4: Make Inferences**\n\nWe assume the null hypothesis is true and we gather evidence against this requirement.  We will find the probability that the mean lead concentration is less than $\\bar x$ = 29.13 mg/kg, assuming that the true mean lead concentration is $\\mu$ = 50 mg/kg.  This probability is called the $P$-value.\n\nSince the sample size is large ($n = 61$), we can conclude that the sample mean is normally distributed.  So, we can use R to find the probability that the sample mean will be less than 29.13.  Historical analyses show that the population standard deviation is $\\sigma$ = 24 mg/kg.\n\nFirst, we compute the $z$-score.\n\n$$z=\\frac{\\bar x-\\mu}{\\sigma / \\sqrt{n} } = \\frac{29.13 - 50}{24 / \\sqrt{61} }=-6.79$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- 29.13\nmu <- 50\nsigma <- 24\nn <- 61\nsigma_xbar <- sigma/sqrt(n)\n\nz <- (x-mu)/sigma_xbar\nz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -6.791663\n```\n\n\n:::\n\n```{.r .cell-code}\npnorm(z)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.542414e-12\n```\n\n\n:::\n:::\n\n\n\n\nUsing the `pnorm()` function, we find the area to the left of $z = -6.79$.  This is the $P$-value.  It is not clear from the image of the applet, but the area to the left was shaded before the $z$-score was entered.\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images/L04_A06_Graph_4.jpg)\n\nThe $P$-value for this test is  so small we have to resort to scientific notation.  $5.54 \\times 10^{-12} = 0.000~000~000~005~6$.  This is a very small probability.  Assuming the null hypothesis is true-that is, the site is unacceptably contaminated-it is very unlikely that we would find such a low mean contamination level among the $n = 61$ randomly selected soil samples.\n\nSince the $P$-value is low, we reject the null hypothesis.\n\n\n<br>\n\n![](https://github.com/byuistats/Math221D_Course/raw/main/Images/Step5.png)\n\n\n**Step 5: Take Action**\n\nThere is sufficient evidence to suggest that the mean lead level is less than 50 mg/kg.  We conclude that the lead concentration in the soil is low enough that it is not a danger to the public.  Based on the results of this and other similar test results, the government has reopened public access to this area.\n\n<br>\n\n## Review of Key Concepts\n\n1. To compute probabilities involving the sample mean $\\bar{x}$ we must first determine if $\\bar{x}$ is normally distributed. If it is not, we cannot compute probabilities. There are two cases when $\\bar{x}$ is guaranteed to be normally distributed. They are:\n\n* The parent population is Normally distributed.\n\n* The Central Limit Theorem guarantees the distribution of $\\bar{x}$ is Normal if the sample size $n$ is large enough. For this course, we require $n \\geq 30$.\n\n2. The collection of all possible sample means $\\bar{x}$ is also a population. The mean of the distribution of sample means is the population mean $\\mu$. The standard deviation of the distribution of sample means is $\\frac{\\sigma}{\\sqrt{n}}$, where $\\sigma$ is the parent population  standard deviation and $n$ is the sample size.\n\n3. Once we have determined that the sample mean is Normally distributed, we can compute probabilities with $\\bar{x}$. We first compute $z = \\frac{\\bar{x} - \\mu}{\\sigma/\\sqrt{n}}$ and then use R to compute probabilities about $z$.\n\n<br>\n\n## Summary\n\n<div class=\"SummaryHeading\">Remember...</div>\n<div class=\"Summary\">\n\n1. A z-score for a sample mean is calculated as:   $\\displaystyle{z = \\frac{\\text{value}-\\text{mean}}{\\text{standard deviation}} = \\frac{\\bar x-\\mu}{\\sigma/\\sqrt{n}}}$\n\n2. When the distribution of sample means is normally distributed, we can use a **z-score** R to calculate the probability that a **sample mean** is above, below or between some given value (or values). \n\n</div>\n<br>\n\n",
    "supporting": [
      "07-Prob_Calculations_for_Means_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}