project:
  type: website
  output-dir: docs

website:
  title: "Math221 Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Textbook"
      menu:
        - text: "Lessons"
        - href: ./01-Course_Intro/Course_Introduction.qmd
        - text: "The Statistical Process"
        - href: ./01-Course_Intro/Stat_Process.qmd

    - text: "Homework"
      menu:
         - text: "Basic Factorial Introduction"

    - text: "R Instructions"
      menu:
        - text: "Installing R"
        - href: ./01-Course_Intro/Installing_R.qmd
        - text: "Intro to R HW"
        - href: ./04-Intro_to_R/Introducing_R_Homework.qmd

    right:
    - text: "Datasets"
      menu:
        - text: "Download Zip Data"

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual
output-dir: docs
