project:
  type: website
  output-dir: docs

website:
  title: "Math221 Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Textbook"
      menu:
        - href: ./Textbook/Course_Introduction.qmd
        - href: ./Textbook/Stat_Process.qmd
        - href: ./Textbook/Shape_and_Center.qmd
        - href: ./Textbook/Spread.qmd
        - href: ./Textbook/Intro_to_Probability.qmd

    - text: "Homework"
      menu:
         - href: ./04-Intro_to_R/Introducing_R_Homework.qmd

    - text: "R Help"
      menu:
        - href: ./01-Course_Intro/Installing_R.qmd
        - href: ./10-Intro_to_Data_Wrangling/Exploring_New_Data_with_Tidyverse.qmd


    right:
    - text: "Datasets"
      menu:
        - text: "Download Zip Data"

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual
output-dir: docs
