project:
  type: website
  output-dir: docs

website:
  title: "Math221 Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Stats Fundamentals"
      menu:
        - href: ./Textbook/Course_Introduction.qmd
        - href: ./Textbook/Stat_Process.qmd
        - href: ./Textbook/Shape_and_Center.qmd
        - href: ./Textbook/Spread.qmd
        - href: ./Textbook/Intro_to_Probability.qmd
        
    - text:  "Workbook"
      menu:
        - href: ./Class_Notes/Installing_R.qmd
        - href: ./Class_Notes/Summarizing_Data_Multiple_Groups.qmd
        - href: ./Class_Notes/Normal_Distribution.qmd
        - href: ./Class_Notes/CLT_Normal_Prob_for_Means.qmd
        - href: ./Class_Notes/Inference_for_mean_sigma_unknown.qmd
        - href: ./Class_Notes/Paired_ttest.qmd
        - href: ./Class_Notes/Independent_2_sample_ttest.qmd
        - href: ./Class_Notes/ANOVA_Intro.qmd
        - href: ./Class_Notes/Assessing_Normality.qmd
        - href: ./Class_Notes/Bivariate_Data_Intro.qmd
        - href: ./Class_Notes/Linear_Regression_Intro.qmd
        - href: ./Class_Notes/Distribution_of_Phat.qmd
        - href: ./Class_Notes/One_Sample_Proportion_Ztest.qmd
        - href: ./Class_Notes/Two_Sample_Proportion_Ztest.qmd
        - href: ./Class_Notes/Chi_Square_Intro.qmd
        
    - text: "Practice Problems"
      menu:
         - href: ./Practice/Introducing_R_Homework.qmd
         - href: ./Practice/Exploring_New_Data_with_Tidyverse.qmd

    - text: "Application Activities"
      menu:
        - href: ./Application_Activities/AA_Data_Summaries.qmd
        - href: ./Application_Activities/AA_Unit1_Review.qmd
        - href: ./Application_Activities/AA_Hypothesis_Conf_Int.qmd
        - href: ./Application_Activities/AA_Unit2_Review.qmd
        - href: ./Application_Activities/AA_Who_Shot_First_Cat_Vars.qmd
        - href: ./Application_Activities/Semester_Project_Instructions.qmd

    - text: "R Help"
      menu:
        - href: ./Class_Notes/Installing_R.qmd


    right:
    - text: "Datasets"
      menu:
        - text: "Download Zip Data"

format:  
  html:
    theme:
      light: flatly
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

output-dir: docs
