project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Student_Work/"
  resources:
    - "Images/**"
    
website:
  title: "Math221D Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Getting Started"
      menu:
        - href: ./1-Getting_Started/1-Course_Intro.qmd
        - href: ./1-Getting_Started/2-Installing_R.qmd
        - href: ./1-Getting_Started/3-Introducing_R.qmd
        - href: ./1-Getting_Started/4-Installing_Packages.qmd
        - href: ./1-Getting_Started/5-Stat_Process.qmd
        - href: ./1-Getting_Started/6-Response_and_Explanatory_Variables.qmd

    - text: "Descriptive Stats"
      menu:
         - text: "Descriptive Statistics"
         - href: ./2-Descriptive_Statistics/1-Numerical_Summaries_Quantitative_Data.qmd
         - href: ./2-Descriptive_Statistics/1-Numerical_Summaries_Quantitative_Data_Practice.qmd
         - href: ./2-Descriptive_Statistics/2-Graphical_Summaries_Quantitative_Data.qmd
         - href: ./2-Descriptive_Statistics/2-Graphical_Summaries_Quantitative_Data_Practice.qmd
         - href: ./2-Descriptive_Statistics/3-Quantitative_Data_Summaries_Multiple_Groups.qmd
         - href: ./2-Descriptive_Statistics/3-Quantitative_Data_Summaries_Multiple_Groups_Practice.qmd
         - href: ./2-Descriptive_Statistics/4-Bivariate_Quantitative_Data_Summaries.qmd
         - href: ./2-Descriptive_Statistics/4-Bivariate_Quantitative_Data_Summaries_Practice.qmd
         - href: ./2-Descriptive_Statistics/5-Univariate_Categorical_Data_Summaries.qmd
         - href: ./2-Descriptive_Statistics/6-Bivariate_Categorical_Data_Summaries.qmd
         - href: ./2-Descriptive_Statistics/6-Categorical_Data_Summaries_Practice.qmd


    - text:  "Data Wrangling"
      menu:
        - text: "Into the Tidyverse"
        - text: "A Better Way to Plot"
          href: ./3-Data_Wrangling_Visualization/1-GGPlot_Intro.qmd
        - href: ./3-Data_Wrangling_Visualization/2-Wrangling_Basics.qmd
        - href: ./3-Data_Wrangling_Visualization/3-Filter.qmd
        - href: ./3-Data_Wrangling_Visualization/4-Select.qmd
        - href: ./3-Data_Wrangling_Visualization/5-Exploring_New_Data_with_Tidyverse.qmd
        - href: ./3-Data_Wrangling_Visualization/6-AA_Data_Wrang_and_Viz.qmd
        - text: "Bonus Material"
        - href: ./3-Data_Wrangling_Visualization/Bonus_More_Tidy_Practice.qmd
        - href: ./3-Data_Wrangling_Visualization/Bonus_Mutate.qmd
        - href: ./3-Data_Wrangling_Visualization/Bonus_GroupBy_Summarise.qmd

    - text: "Inferential Stats"
      menu:
         - text: "Foundations"
         - href: ./4-Foundations_Statistical_Inference/1-Probability.qmd
         - href: ./4-Foundations_Statistical_Inference/2-The_Normal_Distribution.qmd
         - href: ./4-Foundations_Statistical_Inference/2-The_Normal_Distribution_Practice.qmd
         - href: ./4-Foundations_Statistical_Inference/3-Sampling_Distributions_CLT_LLN.qmd
         - href: ./4-Foundations_Statistical_Inference/4-Assessing_Normality.qmd
         - text: "Central Limit Theorem Practice"
           href: ./4-Foundations_Statistical_Inference/6-Central_Limit_Theorem_Practice.qmd
         - href: ./4-Foundations_Statistical_Inference/7-Introducing_Hypothesis_Tests.qmd
         - href: ./4-Foundations_Statistical_Inference/8-Statistical_Significance.qmd
    
  
    - text: "Statistical Tests I"
      menu:
        - href: ./5-Statistical_Tests_Part1/0-Confidence_Intervals_for_Means.qmd
        - href: ./5-Statistical_Tests_Part1/0-Confidence_Intervals_for_Means_Practice.qmd"
        - href: ./5-Statistical_Tests_Part1/1-One_Sample_ttest.qmd
        - href: ./5-Statistical_Tests_Part1/1-One_Sample_ttest_Practice.qmd
        - href: ./5-Statistical_Tests_Part1/2-Conf_Int_Hyp_Test_for_Proportions.qmd
        - href: ./5-Statistical_Tests_Part1/2-Conf_Int_Hyp_Test_for_Proportions_Practice.qmd
        - href: ./5-Statistical_Tests_Part1/3-Two_sample_Independent_ttest.qmd
        - href: ./5-Statistical_Tests_Part1/3-Two_sample_Independent_ttest_practice.qmd
        - href: ./5-Statistical_Tests_Part1/4-Matched_Pairs_ttest.qmd
        - href: ./5-Statistical_Tests_Part1/4-Matched_Pairs_ttest_Practice.qmd
        - href: ./5-Statistical_Tests_Part1/5-Two_sample_Proportions.qmd
        - href: ./5-Statistical_Tests_Part1/5-Two_sample_Proportions_Practice.qmd

    - text: "Statistical Tests II"
      menu:
        - href: ./6-Statistical_Tests_Part2/1-ANOVA.qmd
        - href: ./6-Statistical_Tests_Part2/1-ANOVA_Practice.qmd
        - href: ./6-Statistical_Tests_Part2/2-Regression.qmd
        - href: ./6-Statistical_Tests_Part2/2-Regression_Practice.qmd
        - href: ./6-Statistical_Tests_Part2/3-Chi_Square_Test_of_Independence.qmd
        - href: ./6-Statistical_Tests_Part2/3-Chi_Square_Test_of_Independence_Practice.qmd

    - text: "Semester Project"
      menu:
        - href: ./7-Semester_Project/Data_Search.qmd
        - href: ./7-Semester_Project/Importing_Data.qmd
        - href: ./7-Semester_Project/Semester_Project_Template.qmd

        
    - text: "R Help"
      menu:
        - text: "Tidyverse Cheat Sheet"
          href: https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
        - text: "R for Data Science"
          href: https://r4ds.had.co.nz/transform.html
        - text: "Statistics Notebook - R Commands"
          href: https://byuistats.github.io/Statistics-Notebook/RCommands.html

format:  
  html:
    theme:
      light: flatly
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

output-dir: docs
