project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!Student_Work/"
  resources:
    - "Images/**"
    
website:
  title: "Math221D Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Getting Started"
      menu:
        - href: ./1-Getting_Started/1-Course_Intro.qmd
        - href: ./1-Getting_Started/2-Installing_R.qmd
        - href: ./1-Getting_Started/3-Introducing_R.qmd
        - href: ./1-Getting_Started/4-Installing_Packages.qmd
        - href: ./1-Getting_Started/5-Stat_Process.qmd
        - href: ./1-Getting_Started/6-Response_and_Explanatory_Variables.qmd

    - text: "Descriptive Stats"
      menu:
         - text: "Descriptive Statistics"
         - href: ./2-Descriptive_Statistics/1-Numerical_Quantitative_Data_Summaries.qmd
         - href: ./2-Descriptive_Statistics/1b-Practice_Numerical_Summaries.qmd
         - href: ./2-Descriptive_Statistics/2-Graphical_Quantitative_Data_Summaries.qmd
         - href: ./2-Descriptive_Statistics/2b-Practice_Graphical_Summaries.qmd
         - href: ./2-Descriptive_Statistics/3-Quantitative_Data_Summaries_Multiple_Groups.qmd
         - href: ./2-Descriptive_Statistics/3b-Practice_Quantitative_Summaries_Multiple_Groups.qmd
         - href: ./2-Descriptive_Statistics/4-Bivariate_Quantitative_Data_Summaries.qmd
         - href: ./2-Descriptive_Statistics/4b-Practice_Bivariate_Data.qmd
         - href: ./2-Descriptive_Statistics/5-Univariate_Categorical_Data_Summaries.qmd
         - href: ./2-Descriptive_Statistics/6-Bivariate_Categorical_Data_Summaries.qmd
         - href: ./2-Descriptive_Statistics/6b-Practice_Categorical_Summaries.qmd
         - href: ./2-Descriptive_Statistics/7-AA_Descriptive_Statistics.qmd


    - text:  "Data Wrangling"
      menu:
        - text: "Into the Tidyverse"
        - text: "A Better Way to Plot"
          href: ./3-Data_Wrangling_Visualization/1-GGPlot_Intro.qmd
        - href: ./3-Data_Wrangling_Visualization/2-Wrangling_Basics.qmd
        - href: ./3-Data_Wrangling_Visualization/3-Filter.qmd
        - href: ./3-Data_Wrangling_Visualization/4-Select.qmd
        - href: ./3-Data_Wrangling_Visualization/5-Exploring_New_Data_with_Tidyverse.qmd
        - href: ./3-Data_Wrangling_Visualization/6-AA_Data_Wrang_and_Viz.qmd
        - text: "Bonus Material"
        - href: ./3-Data_Wrangling_Visualization/Bonus_More_Tidy_Practice.qmd
        - href: ./3-Data_Wrangling_Visualization/Bonus_Mutate.qmd
        - href: ./3-Data_Wrangling_Visualization/Bonus_GroupBy_Summarise.qmd

    - text: "Inferential Stats"
      menu:
         - text: "Foundations"
         - href: ./4-Foundations_Statistical_Inference/01-Intro_to_Probability.qmd
         - href: ./4-Foundations_Statistical_Inference/02-The_Normal_Distribution_Textbook.qmd
         - href: ./4-Foundations_Statistical_Inference/03-Normal_Distribution_Workbook.qmd
         - href: ./4-Foundations_Statistical_Inference/04-Normal_Probability_Practice.qmd
         - href: ./4-Foundations_Statistical_Inference/Sampling_Distributions_CLT_LLN_Reading.qmd
         - text: "Central Limit Theorem Practice"
           href: ./4-Foundations_Statistical_Inference/06-Central_Limit_Theorem_Practice.qmd
         - href: ./4-Foundations_Statistical_Inference/07-Prob_Calculations_for_Means.qmd
         - href: ./4-Foundations_Statistical_Inference/08-CLT_Normal_Prob_for_Means.qmd
         - href: ./4-Foundations_Statistical_Inference/09-Prob_Calculations_for_Means_Practice.qmd
         - href: ./4-Foundations_Statistical_Inference/10-Assessing_Normality.qmd        
  
    - text: "Statistical Tests I"
      menu:
        - text: "Introduction to Hypothesis Testing"
          href: ./5-Statistical_Tests_Part1/002-Introduction_to_Inference.qmd
        - text: "Introduction to Confidence Intervals"
          href: ./5-Statistical_Tests_Part1/002-Confidence_Intervals.qmd
        - href: ./5-Statistical_Tests_Part1/01-Inference_for_mean_sigma_unknown.qmd
        - href: ./5-Statistical_Tests_Part1/02-AA_Hypothesis_Conf_Int.qmd
        - text: "Paired T-test"
          href: ./5-Statistical_Tests_Part1/03-Paired_ttest.qmd
        - href: ./5-Statistical_Tests_Part1/04-Paired_ttest_Practice.qmd
        - text: "2-Sample Independent T-test"
          href: ./5-Statistical_Tests_Part1/05-Independent_2_sample_ttest.qmd
        - href: ./5-Statistical_Tests_Part1/06-Independent_2_sample_ttest_practice.qmd
        - href: ./5-Statistical_Tests_Part1/07-ANOVA_Intro.qmd
        - href: ./5-Statistical_Tests_Part1/08-ANOVA_Practice.qmd
        - text: "Comparing Means Activity"
          href: ./5-Statistical_Tests_Part1/09-AA_Unit4_Review.qmd

    - text: "Statistical Tests II"
      menu:
        - href: ./6-Statistical_Tests_Part2/01-Bivariate_Data_Intro.qmd
        - href: ./6-Statistical_Tests_Part2/02-Linear_Regression_Intro.qmd
        - href: ./6-Statistical_Tests_Part2/03-Regression_Practice.qmd
        - href: ./6-Statistical_Tests_Part2/Introducing_Categorical_Data_Analysis.qmd
        - href: ./6-Statistical_Tests_Part2/One_and_Two_Sample_Proportions.qmd
        - href: ./6-Statistical_Tests_Part2/One_and_Two_Sample_Proportion_Practice.qmd
        - href: ./6-Statistical_Tests_Part2/11-Chi_Square_Intro.qmd
        - href: ./6-Statistical_Tests_Part2/12-Chi_Square_Practice.qmd
        - href: ./6-Statistical_Tests_Part2/13-AA_Who_Shot_First_Cat_Vars.qmd
        
    - text: "Inquiry-Based Learning"
      menu:  
        - href: ./8-Inquiry_Based_Learning/Probability.qmd
        - href: ./8-Inquiry_Based_Learning/The_Normal_Distribution.qmd
        - href: ./8-Inquiry_Based_Learning/Sampling_Distributions_CLT_LLN.qmd
        - href: ./8-Inquiry_Based_Learning/Assessing_Normality.qmd
        - href: ./8-Inquiry_Based_Learning/Introducing_Hypothesis_Tests.qmd
        - href: ./8-Inquiry_Based_Learning/Statistical_Significance.qmd

    - text: "R Help"
      menu:
        - text: "Tidyverse Cheat Sheet"
          href: https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
        - text: "R for Data Science"
          href: https://r4ds.had.co.nz/transform.html
        - text: "Statistics Notebook - R Commands"
          href: https://byuistats.github.io/Statistics-Notebook/RCommands.html

format:  
  html:
    theme:
      light: flatly
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

output-dir: docs
