project:
  type: website
  output-dir: docs

website:
  title: "Math221 Notebook"
  navbar:
    background: primary
    search: true
    left:
    - text: "Textbook"
      menu:
        - text: "Course Introduction"
        - href: ./Textbook/Course_Introduction.qmd
        - text: "The Statistical Process"
        - href: ./Textbook/Stat_Process.qmd
        - text: "Shape and Center"
        - href: ./Textbook/Shape_and_Center.qmd
        - text: "Measures of Spread"
        - href: ./Textbook/Spread.qmd
        - text: "Intro to Probability"
        - href: ./Textbook/Intro_to_Probability.qmd

    - text: "Homework"
      menu:
         - text: "Introducing R"
         - href: ./04-Intro_to_R/Introducing_R_Homework.qmd

    - text: "R Help"
      menu:
        - text: "Installing R"
        - href: ./01-Course_Intro/Installing_R.qmd
        - text: "Into the Tidyverse"


    right:
    - text: "Datasets"
      menu:
        - text: "Download Zip Data"

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual
output-dir: docs
