{
  "hash": "9693bb8c527829ce3c25628571d28601",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Simple Linear Regression\"\n---\n\n\n\n\n\n\n\n# Review\n\nConsider the relationship between Score on a math exam and a student's self-reported Confidence Rating.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(mosaic)\nlibrary(rio)\nlibrary(car)\n\nmath <- import('https://byuistats.github.io/BYUI_M221_Book/Data/MathSelfEfficacy.xlsx')\n```\n:::\n\n\n\n\n__Question__: What is the explanatory (aka independent) variable, $x$?  \n__Answer__:  \n\n__Question__: What is the response (aka the dependent) variable, $y$?  \n__Answer__:  \n\n\nPlot the relationship:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(Score ~ ConfidenceRatingMean, data = math)\n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(math, aes(x = ConfidenceRatingMean, y = Score )) +\n  geom_point(color = \"darkblue\") +\n  theme_bw() +\n  labs(\n    title = \"Relationship between Student Confidence Rating in Math and Test Score\"\n  ) \n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n:::\n\n\n\n\n__Question__:  Does the relationship appear linear?  \n__Answer__:  \n\n__Question__: What is the direction of the relationship?\n__Answer__:  \n\n__Question__: What do you think is the strength of the relationship?  (Strong/Moderate/Weak)\n__Answer__:  \n\n__Question__: What is the correlation coefficient, r?\n__Answer__:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor(Score ~ ConfidenceRatingMean, data = math)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7278648\n```\n\n\n:::\n:::\n\n\n\n\n\n# Linear Regression Equation\n\nRecall that the correlation coefficient, $r$, tells us something about the direction and strength of a __linear__ relationship.\n\n\nLinear Regression allows us to find a functional relationship between X and Y:    \n\n$$y = \\beta_0 + \\beta_1x_1 +\\epsilon$$\n\nThis is a reframing of the familiar $y=mx+b$ but we change the intercept and the slope to be Greek letters signifying *population parameters*.  We also add a very important term, $\\epsilon$, which signifies the \"error\" around the line.  Our estimate of error, $\\epsilon$, will be critical to assessing the usefulness of our model.\n\nWe can estimate the slope and intercept of the line that \"best fits\" the data and use that line to make predictions.  \n\n__NOTE__:  As before, Greek letters signify population parameters in statistics while Latin letters are often used for sample statistics.  We estimate $\\beta_0$ and $\\beta_1$ with $b_0$ and $b_1$ respectively. This leads to an equation for predicted values:  \n\n$$\\hat{y}=b_0+b_1x_1$$\nwhere $\\hat{y}$ signifies a predicted value for $y$ for a given $x$.\n\n# In R\n\nRecall that when we had a quantitative response variable and a categorical explanatory variable we could use the `t.test()` if the categorical variable had 2 levels or the `aov()` function if the categorical variable had multiple levels.  We used the same notation for both:  \n<br>\n`t.test(y ~ x, data = dat)` and\n`aov(y ~ x, data = dat)`\n<br>\n\nThe `aov()` function output wasn't as useful as the `t.test()` by itself, so we typically assigned a name to the `aov()` output then used `summarize()` to get the test statistic and p-value.  We could also extract \"residuals\".\n\nThe same paradigm works for estimating the linear relationship between 2 quantitative variables, but we need to introduce a new function:  `lm()`.  The 'lm' stands for \"linear model\".  The relationship notation remains the same:  \n<br>\n`lm(y ~ x, data = dat)`\n<br>\n\nexcept $x$ and $y$ are both quantitative.  Just like with `aov()` the `lm()` output by itself doesn't give us test statistics and p-values.  We will also use the `summarize()` function to get our test statistics.  \n\nLet's fit a linear model estimating the slope and intercept of the line that best fits the relationship between Confidence Rating and Test Score:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmath_lm <- lm(Score ~ ConfidenceRatingMean, data = math)\nsummary(math_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Score ~ ConfidenceRatingMean, data = math)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.200  -6.163   1.292   7.567  23.422 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            18.690      4.610   4.054  8.4e-05 ***\nConfidenceRatingMean   12.695      1.022  12.424  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.27 on 137 degrees of freedom\nMultiple R-squared:  0.5298,\tAdjusted R-squared:  0.5264 \nF-statistic: 154.4 on 1 and 137 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nconfint(math_lm, level = .92)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                          4 %     96 %\n(Intercept)          10.55863 26.82150\nConfidenceRatingMean 10.89262 14.49703\n```\n\n\n:::\n:::\n\n\n\n\nThe `lm()` output includes only the slope and the intercept. \n\n__Question__:  How do we interpret the intercept of 18.69?  \n__Answer__:  \n\n__Question__:  How do we interpret the slope of 12.69 in context?  \n__Answer__:  \n\n__Question__:  What is the expected score on a test of someone who ranks themselves 5 in confidence?  \n__Answer__:  \n\n\n## Plotting the Regression Line\n\n### Base R\n\nScatter plots by themselves are nice, but we would also like to see the regression line.  Simple graphics in R can be augmented by using some functions.  The `abline()` function in base R, when executed right after a graphing function can add lines.  We've used this to add vertical lines and horizontal line already in class.  We can also use this function to add a regression line.  We simply insert our linear model output into the `abline()` function as follows:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(Score ~ ConfidenceRatingMean, data = math)\nabline(math_lm)\n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\nJust as with the other plotting functions we've used, we can change the color, type and width of the line:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(Score ~ ConfidenceRatingMean, data = math, pch = 16, main = \"Title\")\nabline(math_lm, col = \"purple\", lwd = 3, lty = 3)\n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n## GGPlot\n\nUsing `ggplot()`, we can simply add a `geom_smooth()` geometry and specify the method of \"smoothing\" as a linear model:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(math, aes(x = ConfidenceRatingMean, y = Score )) +\n  geom_point(color = \"darkblue\") +\n  theme_bw() +\n  labs(\n    title = \"Relationship between Student Confidence Rating in Math and Test Score\"\n  ) +\n  geom_smooth(method=\"lm\")\n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\nBy default, this gives us a confidence interval for the slope of the regression line.  We can turn that off by forcing the \"standard error\" to be `FALSE`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(math, aes(x = ConfidenceRatingMean, y = Score )) +\n  geom_point(color = \"darkblue\") +\n  theme_bw() +\n  labs(\n    title = \"Relationship between Student Confidence Rating in Math and Test Score\"\n  ) +\n  geom_smooth(method=\"lm\", se = FALSE)\n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n\n\n## Hypothesis Testing for Regression\n\nA linear equation has 2 parameters: Slope and Intercept.  In most situations, the intercept isn't very interesting by itself and is often absurd. We are most often only interested in the slope\n\n$$H_o: \\beta_1 = 0$$\n$$H_a: \\beta_1 \\neq 0$$\n\nThese are the same for all simple linear regression questions.  \n\nTo get the p-value and test statistics, we use the `summary()` function as we did with aov:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(math_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Score ~ ConfidenceRatingMean, data = math)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-38.200  -6.163   1.292   7.567  23.422 \n\nCoefficients:\n                     Estimate Std. Error t value Pr(>|t|)    \n(Intercept)            18.690      4.610   4.054  8.4e-05 ***\nConfidenceRatingMean   12.695      1.022  12.424  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 11.27 on 137 degrees of freedom\nMultiple R-squared:  0.5298,\tAdjusted R-squared:  0.5264 \nF-statistic: 154.4 on 1 and 137 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\nWe can also calculate confidence intervals for the slope by using the `confint()` function.  This function requires you to tell it which model to extract a confidence intervals from.  You can specify which parameter you're interested in, and the level of confidence:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# input the model into the following function:\nconfint(math_lm, level = .95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         2.5 %   97.5 %\n(Intercept)           9.573588 27.80654\nConfidenceRatingMean 10.674297 14.71535\n```\n\n\n:::\n:::\n\n\n\n\n\nHow do we interpret this confidence interval for a slope?\n\nTechnically correct:  95% Confident that the true population slope is within (10.674297, 14.71535)\n\nContextual Explanation:  For every 1 unit increase in Confidence Rating, test scores go up by between (10.674297, 14.71535) on average.  \n\n## Regression Requirements (Is our P-value sus?)\n\nThere are certain requirements for all statistical tests to be valid.  For means, we needed to make sure that the Central Limit Theorem applied.  This meant that we had a large enough sample size (N>30) or that the population itself was normally distributed.  \n\nFor ANOVA, we had to check that the residuals were normally distributed and that the population standard deviations were the same.\n\nRegression analysis has 5 requirements to be valid.  While this sounds daunting, in practice we can check most of them very quickly. \n\n1. Relationship between X and Y is Linear\n2. The residuals, $\\epsilon$, are normally distributed\n3. The Variance of the error terms is constant for all values of X\n4. The X’s are fixed and measured without error (i.e. X’s can be considered as known constants)\n5. The observations are independent\n\nThe linear relationship is assessed visually with the scatter plot.  If there is obvious curvature or non-linearity then fitting a line isn't the best model.\n\nWe check the normality of the residuals with a `qqPlot()` exactly as with the `aov()` output.\n\nRecall that with ANOVA, we had to check that the variation in each group was roughly the same (largest standard deviation was less than twice as large as the smallest standard deviation).  For a quantitative explanatory variable, we can't calculate the standard deviation for a specified level of $x$ because $x$ can be any number.  \n\nConstant variance in regression is checked with a new plot that looks at how the predicted values relate to the residuals.  This is important because we want our predictions to be \"wrong\" about the same regardless of the value of the prediction.  We're looking for random scatter.\n\nRequirement 4 cannot be analyzed directly.  It is important because because $x$ is the independent variable.  If there is uncertainty about the input, then the simple linear regression might not be the most appropriate model.\n\nRequirement 5 also cannot be analyzed, but random sampling usually satisfies this requirement.  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Requirement 1:  Check for linear relationship\nggplot(math, aes(x=ConfidenceRatingMean, y = Score)) + \n  geom_point()\n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Req 2: Normality of residuals:\nqqPlot(math_lm$residuals)\n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 37 89\n```\n\n\n:::\n\n```{.r .cell-code}\n# Req 3: Constant variance (look odd patterns). When you put lm() output into the plot function it gives you several different plots. The residual plots we're most interested in are 1 and 2\n\nplot(math_lm, which = 1)\n```\n\n::: {.cell-output-display}\n![](02-Linear_Regression_Intro_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n:::\n\n\n\n\n# Your Turn\n\nLet's loot at the relationship between Alcohol Consumption compared to life expectancy for selected countries.  \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nalcohol <- import('https://raw.githubusercontent.com/byuistats/Math221D_Cannon/master/Data/life_expectancy_vs_alcohol_consumption.csv')\n```\n:::\n\n\n\n\n__Question__:  What is the repsponse variable?  \n__Answer__:  \n\n__Question__:  What is the explanatory variable?  \n__Answer__:  \n\n\nMake a presentation-worthy scatterplot using `ggplot()` including a regression line:\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n__Question__:  Describe in words the nature of the relationship between the 2 variables (direction/strength/linearity)\n__Answer__:  \n\nCalculate the correlation coefficient:\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n__Question__:  What is the the correlation coefficient, $r$?  \n__Answer__:  \n\nPerform a linear regression analysis for the relationship between alcohol consumption and life expectancy. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Save your linear model:  \n\n# Check for constant variance:  \n\n# Check the normality of the residuals  \n```\n:::\n\n\n\n\n\n__Question__:  What is the slope of the regression line?  \n__Answer__:  \n\n__Question__:  Interpret the slope of the regression line in context of the problem:  \n__Answer__:  \n\n__Question__:  What is the intercept of the regression line?  \n__Answer__:  \n\n__Question__:  Interpret the intercept of the regression line in context of the problem:  \n__Answer__:  \n\n\n__Question__:  What do you conclude about the slope of the regression line?    \n__Answer__:  \n\n__Question__:  What is the confidence interval for the slope? \n\n__Question__:  Give a 1-sentence interpretation of the confidence interval in context of your research question:  \n__Answer__:  \n\n",
    "supporting": [
      "02-Linear_Regression_Intro_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}