{
  "hash": "955541e6a463fd90927e384ef4483cd1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Don't Take it Personally\"\nsubtitle: \"Hypothesis Tests and Confidence Intervals\"\n---\n\n\n\n\n\n\n\n\n# Introduction\n\nIn this activity, you will execute statistical hypothesis tests and generate confidence intervals for each of the Big 5 personality traits using data collected from a random sample of Brother Cannon's Math 221 students.  \n\n__Question__:  What is the population of this analysis?  \n__Answer__:  \n\nFor each personality trait, include:\n\n1. A statement of the null and alternative hypotheses and why you chose the alternative you did.\n1. Choose alpha, $\\alpha = $\n1. Check that you can trust the normality of the mean (`n > 30` or `qqPlot(respons_variable)`)\n1. Run the one-sample t-test and state your conclusion (technical and contextual explanation)\n1. Calculate a $1-\\alpha$ level confidence interval and describe in words what it means in context of the research question\n\nRecall that we can use `favstats()` to get summary statistics, `boxplot()` and `histogram()` to get visualizations, and the `t.test()` function to get hypothesis tests and confidence intervals.  **Be sure to label your plots' axes and include a title.**  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Libraries\n\nlibrary(tidyverse)\nlibrary(mosaic)\nlibrary(rio)\nlibrary(car)\n\n\n# Load Data\nbig5 <- import('https://raw.githubusercontent.com/byuistats/Math221D_Cannon/master/Data/All_class_combined_personality_data.csv')\n```\n:::\n\n\n\n\n\n# Extroversion\n\nState your null and alternative hypotheses:  \n\n$$H_o:  \\mu = 50$$  \n$$H_a:  \\mu > 50$$  \n\n$$\\alpha = 0.025 $$  \n1. Create a table of summary statistics:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extroversion\n\nfavstats(big5$Extroversion) %>% knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|   | min| Q1| median| Q3| max|     mean|       sd|   n| missing|\n|:--|---:|--:|------:|--:|---:|--------:|--------:|---:|-------:|\n|   |   1| 42|     58| 73| 100| 56.98267| 21.09599| 404|       1|\n\n\n:::\n:::\n\n\n\n\n2. Create a histogram of Extroversion:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### I'm making a single variable called \"extrov\" that drops the missing values.  You can do the same thing with the other traits to make analysis a little easier\nextrov <- na.omit(big5$Extroversion) \n\nhistogram(extrov, xlab = \"Extroversion\", main = \"Histogram of Extroversion Percentiles\")\n```\n\n::: {.cell-output-display}\n![](02-AA_Hypothesis_Conf_Int_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n3. Perform the one-sample t.test:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For Hypothesis Test:\nt.test(extrov, mu = 50, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  extrov\nt = 6.6529, df = 403, p-value = 4.697e-11\nalternative hypothesis: true mean is greater than 50\n95 percent confidence interval:\n 55.25232      Inf\nsample estimates:\nmean of x \n 56.98267 \n```\n\n\n:::\n:::\n\n\n\n\n4. Explain your conclusion:  \n\nTechnical:  Because the p-value is less than $\\alpha$, I reject the null hypothesis.  \n\nContextual:  I have sufficient evidence to suggest that Brother Cannon's students are, on average, more Extroverted than the general population.  \n\n5. Create a Confidence Interval for the average extroversion of Brother Cannon's students:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For a Confidence Interval:\nt.test(extrov, conf.level = 1-.025)$conf.int\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 54.62135 59.34399\nattr(,\"conf.level\")\n[1] 0.975\n```\n\n\n:::\n:::\n\n\n\n\n6. Explain your confidence interval:  \n\nI am 97.5% confident that the true average extroversion of Brother Cannon's students is somewhere between the 54.62 and 59.34 percentiles.  \n\n# Agreeableness\n\nState your null and alternative hypotheses.  For example, do you think Brother Cannon's students are more, less, or just different than the general population?  \n\n$$H_o:  \\mu  $$  \n$$H_a:  \\mu $$  \n\n$$\\alpha =  $$    \n1. Create a table of summary statistics for Agreeableness:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n2. Create a histogram of Agreeableness:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n3. Perform the one-sample t.test:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n4. Explain your conclusion:  \n\nTechnical:  \n\nContextual:  \n\n5. Create a Confidence Interval for the average agreeableness of Brother Cannon's students:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For a Confidence Interval:\nt.test()$conf.int\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in t_test.default(): argument \"x\" is missing, with no default\n```\n\n\n:::\n:::\n\n\n\n\n6. Explain your confidence interval:  \n\n\n\n# Openness\nState your null and alternative hypotheses:  \n\n$$H_o:  \\mu $$  \n$$H_a:  \\mu $$  \n\n$$\\alpha = $$  \n\n1. Create a table of summary statistics for Openness:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n2. Create a histogram of Openness:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n3. Perform the one-sample t.test:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n4. Explain your conclusion:  \n\nTechnical:  \n\nContextual:  \n\n5. Create a Confidence Interval for the average openness of Brother Cannon's students:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For a Confidence Interval:\nt.test()$conf.int\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in t_test.default(): argument \"x\" is missing, with no default\n```\n\n\n:::\n:::\n\n\n\n\n6. Explain your confidence interval:  \n\n\n\n# Neuroticism\n\nState your null and alternative hypotheses:  \n\n$$H_o:  \\mu $$  \n$$H_a:  \\mu $$  \n\n$$\\alpha =  $$  \n1. Create a table of summary statistics for Neuroticism:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n2. Create a histogram of Neuroticism:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n3. Perform the one-sample t.test:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n4. Explain your conclusion:  \n\nTechnical:  \n\nContextual:  \n\n5. Create a Confidence Interval for the average neuroticism of Brother Cannon's students:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For a Confidence Interval:\nt.test()$conf.int\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in t_test.default(): argument \"x\" is missing, with no default\n```\n\n\n:::\n:::\n\n\n\n\n6. Explain your confidence interval:  \n\n\n\n# Conscientiousness\n\nState your null and alternative hypotheses:  \n\n$$H_o:  \\mu $$  \n$$H_a:  \\mu $$  \n\n$$\\alpha = $$  \n1. Create a table of summary statistics:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n2. Create a histogram of Conscientiousness:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n3. Perform the one-sample t.test:  \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n4. Explain your conclusion:  \n\nTechnical:  \n\nContextual:  \n\n5. Create a Confidence Interval for the average conscientiousness of Brother Cannon's students:  \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# For a Confidence Interval:\nt.test()$conf.int\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError in t_test.default(): argument \"x\" is missing, with no default\n```\n\n\n:::\n:::\n\n\n\n\n6. Explain your confidence interval:  \n\n\n",
    "supporting": [
      "02-AA_Hypothesis_Conf_Int_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}